# Generated by Django 5.1 on 2024-08-29 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coin', models.TextField()),
                ('value', models.IntegerField()),
                ('date', models.DateField()),
            ],
        ),
    ]
