# Generated by Django 5.1 on 2024-09-01 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='price',
            name='coin',
        ),
        migrations.AddField(
            model_name='price',
            name='currency',
            field=models.TextField(default=50, max_length=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='price',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
