# Generated by Django 5.1 on 2024-09-01 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0003_pi_db_delete_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pi_db',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
