# Generated by Django 5.1 on 2024-09-01 12:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0005_alter_pi_db_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pi_db',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
